"""empty message

Revision ID: 4fce813a7e0e
Revises: f1458db43768
Create Date: 2016-11-09 14:49:05.186810

"""

# revision identifiers, used by Alembic.
revision = '4fce813a7e0e'
down_revision = 'f1458db43768'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identifier', sa.String(length=2000), nullable=True))
    op.create_index(op.f('ix_user_identifier'), 'user', ['identifier'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identifier'), table_name='user')
    op.drop_column('user', 'identifier')
    ### end Alembic commands ###
