"""empty message

Revision ID: caa6fd9f09c1
Revises: None
Create Date: 2016-10-20 13:38:45.101215

"""

# revision identifiers, used by Alembic.
revision = 'caa6fd9f09c1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=2000), nullable=False),
    sa.Column('creator_displayname', sa.String(length=2000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_creator_displayname'), 'list', ['creator_displayname'], unique=False)
    op.create_index(op.f('ix_list_title'), 'list', ['title'], unique=False)
    op.create_table('list_images',
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_images')
    op.drop_index(op.f('ix_list_title'), table_name='list')
    op.drop_index(op.f('ix_list_creator_displayname'), table_name='list')
    op.drop_table('list')
    ### end Alembic commands ###
