"""empty message

Revision ID: cfac71489286
Revises: d92998342804
Create Date: 2016-10-31 15:38:41.676119

"""

# revision identifiers, used by Alembic.
revision = 'cfac71489286'
down_revision = 'd92998342804'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_list_images_uc', 'list_images', ['list_id', 'image_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_list_images_uc', 'list_images', type_='unique')
    ### end Alembic commands ###
