"""empty message

Revision ID: f1458db43768
Revises: cfac71489286
Create Date: 2016-11-09 14:35:02.373957

"""

# revision identifiers, used by Alembic.
revision = 'f1458db43768'
down_revision = 'cfac71489286'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccid', sa.String(length=2000), nullable=False),
    sa.Column('email', sa.String(length=2000), nullable=False),
    sa.Column('nickname', sa.String(length=2000), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ccid'), 'user', ['ccid'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_ccid'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
