# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0002_auto_20161111_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='list',
            name='images',
            field=models.ManyToManyField(related_name='lists', to='imageledger.Image'),
        ),
    ]
