# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0005_auto_20161117_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_synced_with_source',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
