# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0007_auto_20161128_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='removed_from_source',
            field=models.BooleanField(default=False),
        ),
    ]
