# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0008_image_removed_from_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
