# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0010_auto_20161130_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-updated_on']},
        ),
    ]
