# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageledger', '0011_auto_20161205_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='imageledger.Image')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageledger.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usertags',
            unique_together=set([('tag', 'image', 'user')]),
        ),
    ]
