# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageledger', '0014_increase-slug-size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('title', 'owner')]),
        ),
    ]
