# Generated by Django 2.0.1 on 2018-05-08 14:26

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0015_auto_20161219_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='search_vectors',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
