# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('perceptual_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider', models.CharField(blank=True, max_length=80, null=True)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('foreign_identifier', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('foreign_landing_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('filesize', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(max_length=50)),
                ('license_version', models.CharField(blank=True, max_length=25, null=True)),
                ('creator', models.CharField(blank=True, max_length=2000, null=True)),
                ('creator_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('tags_list', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageledger.Image')),
            ],
            options={
                'db_table': 'image_tags',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('creator_displayname', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.NullBooleanField()),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='ListImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageledger.Image')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageledger.List')),
            ],
            options={
                'db_table': 'list_images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='imagetags',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageledger.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='listimages',
            unique_together=set([('list', 'image')]),
        ),
    ]
