# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagetags',
            unique_together=set([('tag', 'image')]),
        ),
    ]
